### ISSUE TITLE
--borderless tag dont work with DarkTitleBar

### ISSUE THREAD

**Issue by Rozbiynk** [Kira-NT/cubes-without-borders#1]
Hi, im using mod version 1.1.0 on minecraft 1.20.1 
If i use --borderless tag in start arguments it still dont open as borderless window
![изображение](https://github.com/Kir-Antipov/cubes-without-borders/assets/95433246/b395f030-c887-40a6-8447-6149ecbb182e)
Im using prism launcher, so i think it may be issue
here is log if it contain anything useful
https://mclo.gs/WZ2Oe0n

**Comment by Rozbiynk** [comment]
issue was in DarkTitleBar

**Comment by Kira-NT** [comment]
I'm glad that the issue has resolved itself :D

So, does the conflict with "DarkTitleBar" only ruin the startup flag functionality? Or the borderless mode doesn't work at all?

**Comment by Rozbiynk** [comment]
it prevent minecraft to launch in borderless mode, but if you manually set it in settings everything is okay. I think you may need put it in mod description

**Comment by Kira-NT** [comment]
The problem is [this piece of code on the `DarkTitleBar`'s side](https://git.froggi.es/williamist/DarkTitleBar/src/commit/feba921c4630bf5b47d0d4d2e417eafb662230e9/src/main/java/tech/williamist/darktitlebar/DarkTitleBar.java#L52-L56):

```java
// this is a very hacky way to invalidate the title bar, so it appears as dark correctly
// without having the user resize the window
int oldWidth = w.getWidth();
w.setWindowedSize(oldWidth + 2, w.getHeight());
w.setWindowedSize(oldWidth, w.getHeight());
```

This by-design forces the window out of the borderless fullscreen mode. So, I would suggest the author of that mod to find a less hacky way of invalidating the title bar :D
