### ISSUE TITLE
Borderless functionality only works on main monitor, when set to second monitor (extended projection) it causes flickers on alt tab/defocus.

### ISSUE THREAD

**Issue by PlayfulPiano** [Kira-NT/cubes-without-borders#12]
Using the latest version for 1.20.2, and I've been experiencing what I described in the title of this issue. Note that this issue in question causes external screenshotting programs to mess up and capture a still of usually either a black screen or the pause menu instead of the game screen proper.

Again, this only happens on external monitors, not the main monitor, when using an "extended" projection. Also on windows 10 if that helps.

**Comment by Kira-NT** [comment]
Hi! Please, try downgrading to v1.0.0 :)

**Comment by PlayfulPiano** [comment]
1.0 seems to have my taskbar get drawn on top of the game client, although it did fix the defocusing flicker.

**Comment by Kira-NT** [comment]
The mod is going to return to how it worked in v1.0.0 no matter what, as v1.1.0 ended up being objectively worse for Windows users. So, let's pretend that v1.1.0 doesn't exist at all and try to find a solution for your problem.

This issue is more of a Windows 10 mandelbug than anything else. Windows 11 doesn't suffer from it, nor did Windows 8.1. Additionally, not all Windows 10 users can reproduce it, so here's that. The taskbar **must** disappear whenever an app takes the whole screen, even if it's not in "exclusive fullscreen" mode. So, here's what you can do:

1. Restart the `explorer.exe` process, which, for some ungodly reason, is both a file manager and a window manager. This will forcibly reload your taskbar *(and your whole desktop, for that matter)*, giving it an opportunity to rethink its life choices and properly update its state.
2. In a less disruptive manner, some users report that simply clicking on the taskbar and then back on the fullscreen app in question may make the taskbar disappear, as losing focus may trigger the necessary update logic.
3. Some users also report that moving the taskbar around *(e.g., to a side/top and then back to the bottom)* made it behave properly for them.
4. Try locking and unlocking the taskbar.
5. Some users also report that the issue may be caused by Nvidia's GeForce In-Game Overlay *(presumably, because it keeps the taskbar in focus all the time)*, so turning it off fixed it for them.

I could also implement a dirty hack that turns a Minecraft window into an always-on-top one while it has focus and then back to normal the second the game loses it. However, this would break other always-on-top windows for users who like to watch videos or whatever on top of their gameplay. So, I don't think I'm gonna do that. Windows 10 is going to reach EOL next year anyways, so there's not much value in adding hacky solutions specifically tied to it.

**Comment by PlayfulPiano** [comment]
Oh, it seems that actually what was causing the issue with regards to 1.0.0 was retrobar drawing on top. Works fine without retrobar.

**Comment by Kira-NT** [comment]
> Works fine without retrobar.

Oh, it makes sense for a third-party app that imitates a taskbar to try to stay always on top. Maybe you can configure its behavior?

**Comment by PlayfulPiano** [comment]
> > Works fine without retrobar.
> 
> Oh, it makes sense for a third-party app that imitates a taskbar to try to stay always on top. Maybe you can configure its behavior?

Had no options related to always on top, although the weird thing is that an external program I use for borderless mc works fine with retrobar, so idk why that's the case.
