### ISSUE TITLE
Flickering when paired with BlurredWindow

### ISSUE THREAD

**Issue by slushieuwu** [Kira-NT/cubes-without-borders#20]
the titlescreen flickers randomly, which is understandable, however ingame there is also flickering

https://github.com/Kir-Antipov/cubes-without-borders/assets/86991346/fe012b2e-24fa-4e15-93da-3f05108d8fbd

https://github.com/Kir-Antipov/cubes-without-borders/assets/86991346/2e4779c5-ee8a-4fc9-9de9-3357e150a6ae

**Comment by slushieuwu** [comment]
![image](https://github.com/Kir-Antipov/cubes-without-borders/assets/86991346/2b89cbf7-84f4-44ca-a340-d705ef3a48d8)
mod list

**Comment by slushieuwu** [comment]
also apologies if this is a bit of dumb ask, i just wanted to use both at the same time, without flickering ingame 
the titlescreen would be nice too, but ill leave that up to you and the developer of blurredwindow :p

**Comment by Kira-NT** [comment]
Thanks for the detailed bug report! I'll look into it. I assume that this `BlurredWindow` of yours uses shaders to achieve this effect and that something in the shader pipeline depends on whether the window is reported as being in fullscreen mode or windowed mode.

Currently, CWB doesn't make the window report itself as being in fullscreen mode when borderless fullscreen is used. This might be what is causing the issue.

**Comment by slushieuwu** [comment]
ive made an issue about compatibility on their end https://github.com/PSJahn/blurredwindow/issues/7

**Comment by Kira-NT** [comment]
Initially, I thought it was a mod that just blurs the panorama, and there might be a problem with how its shader effect interacts with CWB. However, it turns out that it activates the acrylic effect for the entire window using native platform APIs.

The author of the said mod doesn't use anything undocumented; they simply set the value of [`DWMWA_SYSTEMBACKDROP_TYPE`](https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwm_systembackdrop_type) to `DWMSBT_TRANSIENTWINDOW`. If Windows doesn't handle this properly, honestly, it's a Windows issue. This **must** work. I tried the mod on my machine while running Minecraft via XWayland, and it works perfectly without any flickering. So, one possible solution here is to move to Linux :D

In all seriousness, though, I don't think there's a solution, sorry. Well, maybe there's a secret undocumented combination of flags a window should have for this to work properly in a non-windowed and non-exclusive fullscreen mode, but I don't even have a Windows machine to blindly test random configurations until something finally works.

I'm open to cooperation, so if the developer of `BlurredWindow` finds a solution that requires some work on my side, I'm fully on board. But currently, as I don't see a path forward, I'm sadly going to close this as `wontfix`.

By the way, if your only concern is preventing Minecraft from automatically minimizing whenever it loses focus, and you can tolerate some flickering when the game window gains or loses focus *(i.e., **not** while you are actually playing)*, I have another mod called [`Cubes With Borders`](https://github.com/Kir-Antipov/cubes-with-borders). That mod simply tweaks the exclusive fullscreen mode Minecraft already uses, so I think it should work just fine with `BlurredWindow`.

**Comment by slushieuwu** [comment]
ah, id assumed it was windows being a dummy :p

thanks for letting me know about your other mod, ill switch to it, tho i was really hoping for the blur to work with this mod so i could have blur while fullscreened

but windows be windows

**Comment by Kira-NT** [comment]
This mod had more Windows-specific issues than anything else. *Sigh.*

If you don't have a habit of placing PiP and other always-on-top windows on top of your game *(which doesn't work while the game is in exclusive fullscreen mode)*, then Cubes With Borders should suit you, and you should be able to have blur while fullscreened.

**Comment by slushieuwu** [comment]
my biggest gripe with exclusive fullscreen is volume control not showing up while focused :p

other than that - nothing that im _really_ missing

**Comment by slushieuwu** [comment]
hang on ive found an issue with your other mod xd, going to make an issue on it rn
