### ISSUE TITLE
Can't make Minecraft in borderless mode behind other windows (Mac)

### ISSUE THREAD

**Issue by SoupChugger** [Kira-NT/cubes-without-borders#23]
Hi, I'm on Mac using this mod, but in the borderless mode Minecraft is always the only thing visible, even if I tab to other applications: 
<img width="2048" alt="Screenshot 2024-07-15 at 1 55 05 PM" src="https://github.com/user-attachments/assets/451acdb1-58b3-4a0f-a601-6a13158534cd">
Even though I'm on the Chrome window, it's still behind Minecraft. Is there any way I can fix this?

Thank you!

**Comment by Kira-NT** [comment]
Hi! I'll look into it. No ETAs, though, as my only MacBook no longer has macOS installed, and my only friend who daily drives this OS has a pretty tight schedule right now, as they don't have electricity for like 12 hours a day, so I have no good means of physically testing macOS-related stuff at the moment.

**Comment by SoupChugger** [comment]
Hi, please take your time, I'm in no rush at all. And I hope your friend gets electricity back! 😁

**Comment by Kira-NT** [comment]
Thanks! I sure hope that they do too! :)

**Comment by Kira-NT** [comment]
Hello there again! Sorry it took me a while, but I finally managed to thoroughly test the mod on macOS. Indeed, it didn't behave quite as I'd hoped. It turns out that Apple has a pretty funny approach to fullscreen windows - they take up an entire so-called "space" and don't allow other windows to share it *(unless they have a special flag)*. To address this, I modified the fullscreen mode used by CWB on macOS to a sort of "windowed fullscreen" to bypass the issue. Seems to work pretty well. Anyways, let me know if you encounter any other problems!
