### ISSUE TITLE
Breaks Discord game overlay

### ISSUE THREAD

**Issue by Hlebuw3k** [Kira-NT/cubes-without-borders#27]
Enabling the regular or borderless fullscreen settings disables the Disord game overlay and game detection until the setting is disabled AND the game is restarted, does not happen without this mod.

**Comment by Kira-NT** [comment]
I'll check on one thing that *might* be the cause here. However, I wouldn't be too hopeful: if it doesn't end up working, there's nothing I can do about it since Discord Overlay is a piece of proprietary software that doesn't even provide any public APIs one can hook into.

Depending on your use case, you may try [cubes-with-borders](https://github.com/Kir-Antipov/cubes-with-borders), which simply tweaks the regular fullscreen mode so the game doesn't automatically minimize itself whenever its window loses focus. However, be warned that focusing/unfocusing Minecraft's window with it in place will result in a flicker, in case you are sensitive to that. Oh, and don't install both mods side by side, to prevent the issue from persisting due to this mod's mere presence.

**Comment by Hlebuw3k** [comment]
Just to clarify: After enabling either fullscreen or borderless options, Discord stops detecting Minecraft as an application altogether. I can add my browser or the Minecraft launcher as a program to Discord to set it as my status, but Minecraft just disappears. I have tried to use 2 rich presence mods, CraftPresence and Simple Discord RPC, but they don't add back the overlay.

**Comment by Kira-NT** [comment]
Yep, thanks, figured! Are you on Win11?

**Comment by Hlebuw3k** [comment]
Windows 10 Pro 22H2, 64 bit

**Comment by Kira-NT** [comment]
I've reverted the default fullscreen mode used by CWB on Windows back to `windows:windowed`, which should help circumvent your issue.

**Comment by kispintyi** [comment]
Possibly related: #65
