### ISSUE TITLE
Wrong status after hotkey toggle

### ISSUE THREAD

**Issue by Madis0** [Kira-NT/cubes-without-borders#3]
Using version 1.1.0+1.20 on Minecraft 1.20.4.
When the user toggles the full screen via hotkey F11 (and possibly even by forcing it through the launcher, but I didn't test that), then the status ON/OFF/Borderless on vanilla/Sodium video settings becomes incorrect.

**Comment by Kira-NT** [comment]
I will close this one in favor of #2, because technically they are the same thing - when I fix #2, this will go away too automatically.

> and possibly even by forcing it through the launcher, but I didn't test that

It's not really "forcing" the fullscreen mode, launchers just pass the `--fullscreen` flag, which overrides the corresponding window setting saved to a file from the last session. This scenario is handled correctly.
