### ISSUE TITLE
borderless option not appearing with iris 1.8 and sodium 0.6

### ISSUE THREAD

**Issue by sasquott** [Kira-NT/cubes-without-borders#30]
MC version 1.21 & 1.21.1 both showing only on/off radio box for Fullscreen, no Borderless option appearing.

CwB version 2.1.1, tried with and without Reeses options and also Sodium Extra, still no Borderless option

**Comment by sasquott** [comment]
ugh, nvm - must be a mod clash, works fine with just those mods, will post which when I find it

**Comment by sasquott** [comment]
actually, scratch that, it actually works with the options.txt file set to fullscreen mode=2 and fullscreen=false but no menu option shows

**Comment by Kira-NT** [comment]
Also, you can always press <kbd>Shift</kbd> + <kbd>P</kbd> to open the vanilla video settings when you're on the Sodium options screen.

Anyways, if you identify the mod that breaks CWB's Sodium integration, please let me know, and I'll look into it!

**Comment by sasquott** [comment]
hmmm, interesting, so as I've been using this mod for a while, every time I've updated my instance, the setting has always been in the txt file so I haven't noticed this issue. After testing a new install, even with just Sodium 0.6, iris 1.8 and just CWB, I can only see the borderless option if I use shift+p - it's not there on normal sodium menu interface. No other mods involved.
![Screenshot 2024-08-26 104532](https://github.com/user-attachments/assets/2d2ea425-5b55-40f1-8719-ca70f3fde44b)
![Screenshot 2024-08-26 104702](https://github.com/user-attachments/assets/37de36e4-510e-4edc-8467-0eeac3694b88)
![Screenshot 2024-08-26 104719](https://github.com/user-attachments/assets/ac9a0702-e6ad-4f06-839a-0e6092314289)

**Comment by Surgeol** [comment]
yeah, same problem as above, i have sodium 0.6.0beta1, Iris 1.8.0beta3, and mc version 1.21.

**Comment by CottonCandieBoop** [comment]
I get the same issue (it doesn't show in the Sodium menu) but at some point when using the mod long enough without changing anything or actively using the Borderless option, it just gave me the borderless option and I was able to use it. I have no clue what changed, because I just kinda accepted it and moved on until I made a new instance and needed to reapply the setting. The Shift+P thing works great, though!

**Comment by AkalixFrost** [comment]
Getting the same issue as described by others. Only thing related I could find was:
`[17:27:52] [main/WARN]:
@Mixin target me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages was not found cubes-without-borders.sodium.mixins.json:SodiumGameOptionPagesMixin from mod cubes-without-borders`

**Comment by JustablockCode** [comment]
same

**Comment by JustablockCode** [comment]
![image](https://github.com/user-attachments/assets/cb04d83c-d5c9-496a-bc26-9cdb0b1bdd7a)
![image](https://github.com/user-attachments/assets/4d16c8af-372f-4d55-9652-5d1488676d2e)

**Comment by Kira-NT** [comment]
The Sodium mixin no longer works because they've changed the root namespace from `me.jellysquid` to `net.caffeinemc`. I.e., `me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages` no longer exists and should now be referred to as `net.caffeinemc.mods.sodium.client.gui.SodiumGameOptionPages`. I'll update the reference a bit later.

Once again, don't worry, as this doesn't break the mod's functionality. You can still use Shift+P to get to the vanilla settings.

**Comment by Trudol** [comment]
Same problem. Shift+P ain't working. How do i can turn this setting on in config file ?
p.s. Oh. After restart it's on. Fine

**Comment by pikesthefish** [comment]
Can confirm that 0.6.0 makes the mod crash, not the client, since the net.caffeinemc offers only the API and Desktop parts, idk why

**Comment by pikesthefish** [comment]
Any updates on this?

**Comment by DaPiCu** [comment]
The bug still exists in version 0.6... 
easy fix if you switch to Sodium version 0.5, for example.

**Comment by Kira-NT** [comment]
Since `v3.0.0`, the mod has discontinued support for Sodium versions `<=0.5` in favor of version `0.6` and, hopefully, above.
