### ISSUE TITLE
(Feature) Revert to cubes with borders' implementation while in a world?

### ISSUE THREAD

**Issue by slushieuwu** [Kira-NT/cubes-without-borders#34]
Is it possible to have a config option that makes the game revert to cubes with borders' implementation (i.e. exclusive fullscreen when focused) when playing in a world?

If only available while cubes with borders is installed on top of this mod, thats fine.

For example, in the menus, and when paused, always keep the game borderless. When unpaused, switch to exclusive fullscreen mode for reduced input lag.

I feel like this would be a good balance of removing screen flashing when tabbing in and out and reducing input lag, instead adding the flash during pausing/unpausing, when the entire screen is already changing, so it's less obtrusive.

Of course this wouldn't overshadow the main feature of the mod, and it would still be a little clunky, but I feel like it would be a nice option for a happy medium (especially when paired with blurredwindow).

**Comment by Kira-NT** [comment]
While I appreciate the suggested solution, I don't think it's viable to implement.

People typically open Minecraft to, well, play Minecraft - not to stare at the menus. The main complaint about the lack of a Borderless Fullscreen option stems from the need to quickly unfocus the game to, say, click on something or respond to a message, without Minecraft minimizing itself every time, so I doubt many players pause the game before switching to other tasks, especially since they usually only need to divert their attention for a few seconds. Plus, it doesn't even work in multiplayer when playing on a server with friends. Also, let me remind you that these problems are only relevant for *Windows* users.

So, while the proposed solution might alleviate some issues, it's quite limited in its scope. To be quite frankly honest with you, I don't think it's worth investing my two hours of free time per day to implement.

As for the input lag, since the last time I worked on this mod, I've come to terms with the fact that there's no perfect solution for Windows users. The combination of GLFW bugs, driver issues, and the overall absolute madhouse that is Windows makes it nearly impossible to fix everything simultaneously, simply because solutions to some of the problems are mutually exclusive. Therefore, the next version will include a configuration screen where users can choose the type of "borderless fullscreen" that best suits their needs. Sigh.

Regarding the compatibility issues with blurredwindow *(once again, this is only a Windows problem - it works fine on X11)*, you might want to suggest the same solution to the author of that mod. If I recall correctly, the window only needs to be translucent when a menu screen is open, not while you're actually playing the game, right?

**Comment by Kira-NT** [comment]
I've had some time to think about this suggestion while revamping CWB, and I don't think I'd even accept a PR if someone else implemented this feature.

The main reason for even considering this feature, as you yourself suggested, would be to address the screen flashing when the game window gains or loses focus without losing on the in-game input lag "benefits". However, this approach would only work if the player deliberately pressed <kbd>ESC</kbd> each time they wanted to switch to another window, bringing up the Pause menu first. If we try to toggle the fullscreen type on the fly based solely on whether the game has focus, the switch will always happen too late for it to count. Essentially, we can't handle this correctly without knowing the player's intentions in advance *(i.e., reading their mind)*.

So, it is what it is. With our current setup *(GLFW+Windows)*, there is just no perfect solution that wouldn't have any drawbacks.

In `v3.0.0`, I've added a configuration screen where you can choose your preferred fullscreen type. This is the best I can do to try to accommodate everyone's preferences.
