### ISSUE TITLE
No Borderless on Sodium 0.5.11 version

### ISSUE THREAD

**Issue by FelixAgairu** [Kira-NT/cubes-without-borders#37]
MC 1.21.1
Fabric 0.16.7
Sodium 0.5.11

![Untitled](https://github.com/user-attachments/assets/cd188836-c07b-4a4c-aa7e-e177136ffc13)

**Comment by Kira-NT** [comment]
Hi! Yup, as of 69576dcf0f5aafe03ab25fcabf8de0affa5eeee7, this behavior is expected. I couldn't maintain support for Sodium 0.5 because Jelly has moved the entire thing to a new namespace. While we are in this weird transitional phase, where you can load two entirely different major versions of Sodium, you basically have three options:

- Update Sodium to 0.6.
- Temporarily downgrade CWB.
- Ignore this minor inconvenience for now. Sodium support is purely cosmetic, and you can always ensure you have the correct fullscreen mode enabled in vanilla Video Settings, which you can access by pressing <kbd>Shift</kbd>+<kbd>P</kbd> while in Jelly's Options Page. You're likely already using borderless fullscreen, so the toggle in Sodium Game Options will simply switch between windowed and borderless fullscreen.
