### ISSUE TITLE
Will installing this mod allow xbox game bar to work with MC Java?

### ISSUE THREAD

**Issue by TechPro424** [Kira-NT/cubes-without-borders#6]

**Comment by Kira-NT** [comment]
To be quite frankly honest with you, I have absolutely no idea what "xbox game bar" is. If it's an overlay-like application that previously failed to function because Minecraft didn't permit anything to be rendered atop it while in "true fullscreen" mode, then yes, this should fix the issue. In borderless (aka windowed) fullscreen mode, any application, including Minecraft, can be overlapped by other apps. However, if there are additional aspects to consider, then the answer is no, as this mod doesn't offer any specific fixes for third-party applications.

So, to get a definitive answer, I suggest giving it a try yourself :) Let me know how it goes!

**Comment by TechPro424** [comment]
Doesn't look like it worked
xbox game bar gives me a message saying "Choosing full screen borderless in your game's video settings might do the trick."

Xbox Game Bar is an overlay in Windows 10 and 11 that allows users to capture and record their gameplay, while also having other minor utilities

**Comment by Kira-NT** [comment]
So, here's what I've [found](https://support.xbox.com/en-US/help/friends-social-activity/share-socialize/record-game-clips-game-bar-windows-10):

> For some PC games, Game Bar won’t appear in full screen mode. To start and stop recordings without Game Bar, use the keyboard shortcut **Windows logo key <kbd>Win</kbd> + <kbd>Alt</kbd> + <kbd>R</kbd>**. The screen will flash to indicate the start and end of recording. If background recording is on, **Windows logo key <kbd>Win</kbd> + <kbd>Alt</kbd> + <kbd>G</kbd>** will record the last moments of play.
>
> If the shortcuts don’t work for a full-screen game, press the **Windows logo key <kbd>Win</kbd> + <kbd>G</kbd>**. The screen will flash twice to confirm that the game is recognized. Then, re-open the game in full screen mode.

But I think you already know that much better than I do. So, since nothing from this works for you, my guess is that it's not really a fullscreen-related issue. As you may know, when you play Minecraft, there's no "minecraft.exe" process that can be easily detected by programs like Xbox Game Bar. Minecraft is run on JVM, so the actual executable you are running on your machine is just "java". The same applies to, for example, a card game named Slay the Spire, any IDE from JetBrains, some obscure GUI app you got from GitHub, and so on and so forth.

So, I can see why Xbox Game Bar doesn't detect Minecraft as a game, although it's still quite surprising. I would expect it, as it's created and owned by Microsoft, to be compatible with Minecraft, which they also own and milk into oblivion, out of the box no matter what. But oh well.

I have a friend with a Windows machine, so I can get back to this issue later and try some things to fix it. No promises and/or ETAs though.

**Comment by Kira-NT** [comment]
I finally got my Windows friend to test this for me, and yep, it works with `v1.0.0`. `v1.1.0` is slightly borked at the moment, but the upcoming `v2.0.0` will also make Xbox Game Bar work with Minecraft.

**Comment by TechPro424** [comment]
Good to know 👍

**Comment by Kira-NT** [comment]
Fixed in `v2.0.0`.
