### ISSUE TITLE
Backport for 1.18.2

### ISSUE THREAD

**Issue by Nukecraft5419** [Kira-NT/cubes-without-borders#9]
Will a backport for fabric 1.18.2 be coming?

**Comment by Kira-NT** [comment]
Yup. The mod is pretty lightweight, so I plan to backport it all the way to 1.14 *(the first Minecraft version officially supported by Fabric)*. I want to resolve the current issues and implement the remaining features first, so that I can backport a single near-perfect version and never touch it ever again :)

**Comment by Nukecraft5419** [comment]
Is there anything I can do to help I'm a Full-Stack developer I've never developed mods yet although I'm in the process of doing so, so I could use to learn

**Comment by Kira-NT** [comment]
Thank you for the consideration! However, there's nothing that requires assistance here, really. It's more about me just getting some time with this project :)

**Comment by Kira-NT** [comment]
The mod has been ported to all Minecraft versions starting from 1.16.5 and is now compatible with every mod loader known to man.
